services:
  db:
    image: postgres:16
    container_name: buyria_db
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "7432:5432"

  redis:
    image: redis:latest
    container_name: buyria_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    image: buyria_app:latest
    container_name: buyria_web
    volumes:
      - .:/code  
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
      - redis
    command: sh run_web.sh

  celery_worker:
    build: .
    image: buyria_app:latest
    container_name: buyria_worker
    restart: always
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    command: celery -A ecommerce worker --loglevel=info
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    image: buyria_app:latest
    container_name: buyria_beat
    restart: always
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    command: celery -A ecommerce beat -s /tmp/celerybeat-schedule
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  redis_data: